### ISSUE TITLE
URL expired

### ISSUE THREAD

**Issue by BlaiseKelly** [Robinlovelace/odjitter#11]
In the script getdata.R the URL http://www.scotlandscensus.gov.uk/documents/additional_tables/WU03BSC_IZ2011_Scotland.xlsx no longer works.

**Comment by Robinlovelace** [comment]
Thanks for the heads-up @BlaiseKelly and sorry for the slow response. I think the same dataset can be acquired from here (but not sure): https://www.nomisweb.co.uk/census/2011/wf02ew 

Any ideas how best to address this, e.g. replace the old one with that?

**Comment by BlaiseKelly** [comment]
I did spend some time looking for a replacement, but I don't really know what is in the table. I found WU03xx but it didn't include Scotland. Is there maybe a copy of the original table that can be added to the repository temporarily and then I will find an online version? Googling WU03BSC_IZ2011.xlsx doesn't bring up anything.

**Comment by BlaiseKelly** [comment]
nr scotland have removed all the tables from the 2011 census. Obtained a local copy of the file, added to folder and amended script to use this instead.
